version: '3.8'

services:
  transaction:
    build:
      context: ./app
    volumes:
      - ./app:/app/app
    ports:
      - "8000:8000"
    environment:
      REDIS_URL: ${REDIS_URL}
      DATABASE_URL: ${DATABASE_URL}
      USE_POSTGRES: ${USE_POSTGRES}
    depends_on:
      - redis
      - db

  celery:
    build:
      context: ./app
    volumes:
      - ./app:/app/app
    command: celery -A app.tasks.app worker --loglevel=info -E
    environment:
      REDIS_URL: ${REDIS_URL}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - redis
      - db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
